If statement

In [3]:
car = 'BMW'
if car == 'BMW' :
    print ('Yes It is')

Yes It is


In [ ]:
car = 'BMW'
if True:
    print ('Yes')

In [ ]:
Car = 'BMW'
if car:
    print ('yes')

In [ ]:
age = int(input('How old are you?'))
if 60 >= float(age) > 30:
    print ('You still Young mann')
elif age < 30:
    print ('You are so young')
else:
    print ('Sorry, you are a bit old')

In [ ]:
age = int(input('How old are you?'))
if 60 >= age >= 25:
    print ('You are still young mann!!')
elif age < 25:
    print ('You are a bit younger than we need')
else:
    print ('A bit older than we need, sorry!!')        

In [ ]:
Mobile_price = int(input('What is the price you need'))
if 10000 >= Mobile_price >= 5000:
    print ('Samsong, HTCS, Huawi, Xaumi, Sony')
elif Mobile_price < 5000:
    print ('Nokia')
else:
    print ('iPhone')        

In [ ]:
price = int(input(' What is the price you need?'))
if 15000 >= price >= 7500:
    print ('Samsung, Xaumi, Huawi, HTCS, Relmea, Sony')
elif 7500 > price > 5000:
    print ('Sony')
elif price < 5000:
    print ('Nokia') 
else:
    print ('iPhone')            

In [ ]:
price = int(input('What is the price do you want?'))
if 20000>= price >= 12500:
    print  ('Xaomi, HTCS, Infinx, Huawi, Sony')
elif 12500 > price >= 7500:
    print ('Xaomi, HTCS, Infinx, Huawi, Relmea, Oppo, Redmei')
elif price < 7500:
    print ('Nokia')
else:
    print ('iPhone')            

Variable Scope

In [ ]:
def greet ():
    name = 'Omaran'
    print (f"Hello, {name}")
greet()    

Anonymous Functions (Lambda)

In [ ]:
add = lambda a, b : a +b
print(add(5,16))

Higher-Order Functions

In [ ]:
numbers = [1, 3, 4, 6, 8, 9]
squared = list(map(lambda x: x**2, numbers))
print (squared)

In [ ]:
numbers = [1, 3, 4, 6, 7, 9]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print (even_numbers)

In [ ]:
numbers = [1, 5, 7, 8, 10, 11, 15]
odd_numbers = list(filter(lambda x: x % 1 == 0, numbers))
print(odd_numbers)

In [ ]:
Iterators

In [ ]:
numbers = [1, 3, 4, 6, 7]
it = iter(numbers)

print (next(it))
print (next(it))

Generators

In [ ]:
def countdoun (n):
    while n > 0:
        yield n
        n -= 1
for number in countdoun(5):
    print(number)        


In [ ]:
def countdoun (R):
    while R > 3:
        yield R
        R -= 2

for number in countdoun(12):
    print (number)


In [4]:
def countdoun(a):
    while 4 <= a <= 100:
        yield a
        a -= 7
for number in countdoun (21):
    print(number)         

21
14
7


In [ ]:
try:
    result = 10 / 2
    print (result)
except ZeroDivisionError:
    print("You can't divide by zero!")

In [ ]:
try:
    result = 10 / 0
except ZeroDivisionError:
    print("You can't divide by zero!")

In [2]:
try:
    result = 10 / 5
except ZeroDivisionError:
    print ("You can not dive by zero")
else:
    print (result)
finally:
    print ('It will always run')

2.0
It will always run


In [1]:
def check_age(age):
    if age <= 18:
        raise ValueError ('age must be 18 at least')
    return True
check_age(22)

True

List Comprehensions

In [5]:
squares = [x**2 for x in range (5)]
print (squares)

[0, 1, 4, 9, 16]


In [7]:
squares_dict = {x: x**2 for x in range (5)}
print (squares_dict)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}


Lambda Functions

In [1]:
add = (lambda a, b : a + b)
print (add(1, 5))

6


In [2]:
add = (lambda x, y : x * y)
print (add(2,7))

14


Sorting Data

In [10]:
import pandas as pd

data = {
    "ProductID": [101, 102, 103, 104],
    "SalesAmount": [200, 150, 400, 300],
    "Region": ["North", "South", "West", "East"]
}

df = pd.DataFrame(data)
sorted_df = df.sort_values(by ='SalesAmount')
print(sorted_df)

   ProductID  SalesAmount Region
1        102          150  South
0        101          200  North
3        104          300   East
2        103          400   West


Filtering Data

Boolean Indexing (>, <, ==, etc.)

In [7]:
filtered_df = df[df['SalesAmount'] >= 200]
print(filtered_df)

   ProductID  SalesAmount Region
0        101          200  North
2        103          400   West
3        104          300   East


In [8]:
filtered_dt = df[(df['SalesAmount'] > 200) & (df['Region'] == 'West')]
print(filtered_dt)

   ProductID  SalesAmount Region
2        103          400   West


Filtering Using isin()

In [9]:
data_filtered = df[df['Region'].isin(['West', 'North'])]
print (data_filtered)

   ProductID  SalesAmount Region
0        101          200  North
2        103          400   West


Filtering with query()

In [10]:
dataframe_filtered = df.query('SalesAmount > 200 and Region == "West"')
print (dataframe_filtered)

   ProductID  SalesAmount Region
2        103          400   West


Applying Functions to Data

In [17]:
def add_sale(sales):
    return sales * .75

df['Black_Friday_sale'] = df['SalesAmount'].apply(add_sale)
print(df)

   ProductID  SalesAmount Region  SalesWithTax   Sale  Black_Friday_sale
0        101          200  North         220.0  220.0              150.0
1        102          150  South         165.0  165.0              112.5
2        103          400   West         440.0  440.0              300.0
3        104          300   East         330.0  330.0              225.0


Aggregation with groupby()

In [20]:
data_grouped = df.groupby('Region')['SalesAmount'].sum()
print(data_grouped)

Region
East     300
North    200
South    150
West     400
Name: SalesAmount, dtype: int64


Handling Duplicates

In [24]:
duplicates = df.duplicated()
print(duplicates)

0    False
1    False
2    False
3    False
dtype: bool


In [25]:
no_df_duplicates = df.drop_duplicates('Region')
print(no_df_duplicates)

   ProductID  SalesAmount Region  SalesWithTax   Sale  Black_Friday_sale
0        101          200  North         220.0  220.0              150.0
1        102          150  South         165.0  165.0              112.5
2        103          400   West         440.0  440.0              300.0
3        104          300   East         330.0  330.0              225.0


Basic Statistical Operations

In [27]:
df_mean = df['SalesAmount'].mean()
print(df_mean)

262.5


In [ ]:
print (df.describe())

        ProductID  SalesAmount  SalesWithTax        Sale  Black_Friday_sale
count    4.000000     4.000000      4.000000    4.000000           4.000000
mean   102.500000   262.500000    288.750000  288.750000         196.875000
std      1.290994   110.867789    121.954568  121.954568          83.150842
min    101.000000   150.000000    165.000000  165.000000         112.500000
25%    101.750000   187.500000    206.250000  206.250000         140.625000
50%    102.500000   250.000000    275.000000  275.000000         187.500000
75%    103.250000   325.000000    357.500000  357.500000         243.750000
max    104.000000   400.000000    440.000000  440.000000         300.000000


In [31]:
total_sales = df['SalesAmount'].sum()
print(total_sales)

1050


Identifying Missing Data

In [2]:
print (df.isnull())

   ProductID  SalesAmount  Region
0      False        False   False
1      False        False   False
2      False        False   False
3      False        False   False


In [6]:
print (df.isnull().sum())

ProductID      0
SalesAmount    0
Region         0
dtype: int64


In [8]:
data1 = {
    "ProductID": [101, 102, 103, 104],
    "SalesAmount": [200, None, 400, 300],
    "Region": ["North", "South", None, "East"]
}

dt = pd.DataFrame(data1)
print (dt)

   ProductID  SalesAmount Region
0        101        200.0  North
1        102          NaN  South
2        103        400.0   None
3        104        300.0   East


In [9]:
print (dt.isnull())

   ProductID  SalesAmount  Region
0      False        False   False
1      False         True   False
2      False        False    True
3      False        False   False


Removing Missing Data

In [11]:
dt_cleaned = dt.dropna()
print (dt_cleaned)

   ProductID  SalesAmount Region
0        101        200.0  North
3        104        300.0   East


In [12]:
dt_column = dt.dropna(axis = 1)
print (dt_column)

   ProductID
0        101
1        102
2        103
3        104


Controlling the Threshold with thresh

In [14]:
df_thresh = df.dropna(thresh = 2)
print (df_thresh)

   ProductID  SalesAmount Region
0        101          200  North
1        102          150  South
2        103          400   West
3        104          300   East


Imputing Missing Data

In [16]:
mean_df = df['SalesAmount'].mean()
filled_df = df['SalesAmount'].fillna(mean_df)
print(filled_df)

0    200
1    150
2    400
3    300
Name: SalesAmount, dtype: int64


In [18]:
df_filled_backward = df.fillna(method='bfill')
print (df_filled_backward)

   ProductID  SalesAmount Region
0        101          200  North
1        102          150  South
2        103          400   West
3        104          300   East


Advanced Imputation Techniques: Interpolation

In [20]:
df_interpolation = df['SalesAmount'].interpolate()
print (df_interpolation)

0    200
1    150
2    400
3    300
Name: SalesAmount, dtype: int64


jupyter notebook --port=8890

In [1]:
import pandas as pd

df1 = pd.DataFrame({
    'ProductID': [101, 102, 103],
    'SalesAmount': [200, 150, 400]
})

df2 = pd.DataFrame({
    'ProductID': [102, 103, 104],
    'Region': ['North', 'South', 'East']
})

Merging DataFrames

In [2]:
merged_df = pd.merge(df1, df2, on='ProductID', how='inner')
print(merged_df)

   ProductID  SalesAmount Region
0        102          150  North
1        103          400  South


In [4]:
import pandas as pd
merged_df_inner = pd.merge(df1, df2, on = 'ProductID', how= 'inner')
print(merged_df_inner)

   ProductID  SalesAmount Region
0        102          150  North
1        103          400  South


In [5]:
import pandas as pd
merged_df_left = pd.merge(df1, df2, on = 'ProductID', how= 'left')
print(merged_df_left)

   ProductID  SalesAmount Region
0        101          200    NaN
1        102          150  North
2        103          400  South


In [6]:
import pandas as pd
merged_df_right = pd.merge(df1, df2, on = 'ProductID', how= 'right')
print(merged_df_right)

   ProductID  SalesAmount Region
0        102        150.0  North
1        103        400.0  South
2        104          NaN   East


Concatenating DataFrames

In [7]:
df3 = pd.DataFrame ({
    'ProductID': [105, 106],
    'SalesAmount': [250, 350]
})

In [8]:
concatenated_df = pd.concat([df1, df3], ignore_index = True)
print(concatenated_df)

   ProductID  SalesAmount
0        101          200
1        102          150
2        103          400
3        105          250
4        106          350


joining DataFrame

In [2]:
df1.set_index('ProductID', inplace =True)
df2.set_index('ProductID', inplace = True)

df_joined = df1.join(df2, how= 'inner')
print(df_joined)

           SalesAmount Region
ProductID                    
102                150  North
103                400  South


Reshaping DataFrames

In [3]:
data = {
    "Date": ["2024-01-01", "2024-01-01", "2024-01-02", "2024-01-02"],
    "Product": ["A", "B", "A", "B"],
    "SalesAmount": [100, 200, 150, 250]
}

In [4]:
dt = pd.DataFrame(data)

In [6]:
dt_pivot = dt.pivot(index = 'Date', columns = 'Product', values = 'SalesAmount')
print (dt_pivot)

Product       A    B
Date                
2024-01-01  100  200
2024-01-02  150  250


Stacking and Unstacking

In [7]:
df_multi = pd.DataFrame({
    ('Region', 'North'): [200, 300],
    ('Region', 'South'): [150, 400]
}, index=['Product1', 'Product2'])

In [8]:
df_stack = df_multi.stack()
print(df_multi)

         Region      
          North South
Product1    200   150
Product2    300   400


Pivoting and Melting Data

In [12]:
df_pivot_table = pd.pivot_table(df, values='SalesAmount', index='ProductID', columns='Region', aggfunc='sum')
print(df_pivot_table)

Region      East  North  South   West
ProductID                            
101          NaN  200.0    NaN    NaN
102          NaN    NaN  150.0    NaN
103          NaN    NaN    NaN  400.0
104        300.0    NaN    NaN    NaN


What is a NumPy Array?

In [1]:
import numpy as np

In [2]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_1d)
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


Arithmetic Operations

In [3]:
arr = np.array([1, 2, 3, 6])
arr_add = arr + 5
print (arr_add)

[ 6  7  8 11]


In [4]:
# Access specific elements
print (arr[0])

1


In [5]:
# for the 2d array
print (arr_2d[:, 2])

[3 6]


In [6]:
print (arr_2d[0, :])

[1 2 3]


Broadcasting

In [9]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([[10], [20], [30]])

result = arr_1 + arr_2
print (result)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [13]:
result2 = arr_1 * arr_2
print (result2)

[[10 20 30]
 [20 40 60]
 [30 60 90]]


Common Functions and Methods

In [15]:
mean_val = np.mean(arr)
sum_val = np.sum(arr)
print (mean_val)
print (sum_val)

3.0
12


Reshaping Arrays

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [21]:
arr_reshaped = arr.reshape(2, 3)
print (arr_reshaped)

[[1 2 3]
 [4 5 6]]


Generating Random Numbers

In [22]:
# Generate an array of random numbers between 0 and 1
random_arr = np.random.rand(3, 3)
print(random_arr)

# Generate random integers
random_ints = np.random.randint(1, 10, size=(2, 3))
print(random_ints)

[[0.77752637 0.52811159 0.10450507]
 [0.15894264 0.27180292 0.31291016]
 [0.19665938 0.59609144 0.34129462]]
[[3 4 5]
 [6 8 2]]


Summary Statistics Using Pandas

In [23]:
import pandas as pd

# Sample DataFrame
data = {
    "ProductID": [101, 102, 103, 104],
    "SalesAmount": [200, 150, 400, 300],
    "Region": ["North", "South", "West", "East"]
}

df = pd.DataFrame(data)

summery = df.describe()
print(summery)

        ProductID  SalesAmount
count    4.000000     4.000000
mean   102.500000   262.500000
std      1.290994   110.867789
min    101.000000   150.000000
25%    101.750000   187.500000
50%    102.500000   250.000000
75%    103.250000   325.000000
max    104.000000   400.000000


Visualizing Data Distributions